### ISSUE TITLE
 Implement 'justify-content' Section in Flexbox Visualizer

### ISSUE THREAD

**Issue by imran-khani** [fahdi/css-visual-learner#21]
The objective is to enrich the Flexbox visualizer by introducing a dedicated 'justify-content' section. This addition aims to empower users with interactive options to understand the behavior and impact of various 'justify-content' properties within the Flexbox layout.

**Proposed Changes:**

1. **HTML Modification:**
   - Integration of the 'justify-content' section into `flex-box.html`, featuring a select element showcasing different 'justify-content' options.

2. **CSS Adjustments:**
   - Updates in `style.css` and `flexbox.css` to ensure harmonious styling and seamless presentation of the new 'justify-content' section.

3. **JavaScript Implementation:**
   - Addition of an event listener in `flexbox.js` to dynamically manage changes in 'justify-content' selections, enabling real-time updates to the layout.

**Objective:**
This enhancement aims to augment the learning experience for users by enabling them to interactively explore and comprehend the effects of 'justify-content' properties in a Flexbox layout.

**Requested Review Emphasis:**
Kindly focus the review on assessing the functionality of the 'justify-content' section. Evaluate its integration with existing code, coherence in CSS styling, and the efficacy of the JavaScript implementation for facilitating real-time updates based on 'justify-content' selections.

**Comment by fahdi** [comment]
@imran-khani  An issue should not have a PR description. It should describe what is supposed to be done and why!

**Comment by imran-khani** [comment]
Sure.
