### ISSUE TITLE
Bug in Animations Visualizer 

### ISSUE THREAD

**Issue by alihassancods** [fahdi/css-visual-learner#72]
@fahdi 
---
name: Bug report in Animations.js
about: 'Animations Visualizer' 
title: 'Bug in Animations Visualizer'
labels: ''
assignees: ''

---

**Bug Description**
This bug is caused by line 3,4,5 in animations .js which are
` if (window.location.pathname !== '/animations.html') {
    return;
  }`
Due to these lines the Js files terminates at the start by returning nothing. This is because the url of the css visual learner is according to template fahdi.github.io/css-visual-learner/{file-name} and it doesn't matches the url mentioned in JS File.

**To Reproduce**
1. Go to 'https://fahdi.github.io/css-visual-learner/animations.html'
2. Click on 'apply animation' button or any button next to it. None of them will work.

**Expected behavior**
The Javascript file should run the animations on the page.

**Screenshots**
![Screenshot_2023-11-29_00_15_34](https://github.com/fahdi/css-visual-learner/assets/124016531/b04f9910-3947-485b-b4e5-0d172d0a9951)
![Screenshot_2023-11-29_00_17_18](https://github.com/fahdi/css-visual-learner/assets/124016531/02a6421f-90b8-4ff6-a5a7-dbe18239f74f)

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Browser: Firefox
 - Version 91.8.0

**Comment by fahdi** [comment]
@AliCodingGuru Feel free to update the PR and open it again.
